In [1]:
import pandas as pd

In [2]:
df_gu = pd.read_csv("/Users/sangu/likelion_AIS/ais7/mid_project/mid_data/LOCAL_PEOPLE_GU_2021.csv", encoding = "cp949")

In [3]:
df_gu["자치구코드"]

0         11110
1         11140
2         11170
3         11200
4         11215
          ...
218995    11620
218996    11650
218997    11680
218998    11710
218999    11740
Name: 자치구코드, Length: 219000, dtype: int64

In [4]:
df_gu[df_gu["자치구코드"] == "11110"]

Empty DataFrame
Columns: [기준일ID, 시간대구분, 자치구코드, 총생활인구수, 남자0세부터9세생활인구수, 남자10세부터14세생활인구수, 남자15세부터19세생활인구수, 남자20세부터24세생활인구수, 남자25세부터29세생활인구수, 남자30세부터34세생활인구수, 남자35세부터39세생활인구수, 남자40세부터44세생활인구수, 남자45세부터49세생활인구수, 남자50세부터54세생활인구수, 남자55세부터59세생활인구수, 남자60세부터64세생활인구수, 남자65세부터69세생활인구수, 남자70세이상생활인구수, 여자0세부터9세생활인구수, 여자10세부터14세생활인구수, 여자15세부터19세생활인구수, 여자20세부터24세생활인구수, 여자25세부터29세생활인구수, 여자30세부터34세생활인구수, 여자35세부터39세생활인구수, 여자40세부터44세생활인구수, 여자45세부터49세생활인구수, 여자50세부터54세생활인구수, 여자55세부터59세생활인구수, 여자60세부터64세생활인구수, 여자65세부터69세생활인구수, 여자70세이상생활인구수]
Index: []

[0 rows x 32 columns]

In [5]:
df_gu["자치구코드"] == 11110

0          True
1         False
2         False
3         False
4         False
          ...
218995    False
218996    False
218997    False
218998    False
218999    False
Name: 자치구코드, Length: 219000, dtype: bool

In [6]:
import pandas as pd

df = pd.DataFrame([{"country":"한국","population":500},{"country":"미국","population":450},{"country":"싱가폴","population":705},
                   {"country":"호주","population":878},{"country":"베트남","population":660},{"country":"대만","population":808}])

In [7]:
df_gu[df_gu['자치구코드'] == 11110]

,기준일ID,시간대구분,자치구코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20210101,0,11110,194924.6184,4920.3837,2992.2011,4479.0239,7799.4338,8270.0476,6591.1392,...,7513.2691,6532.6210,7281.9873,7159.4938,8479.3144,7389.4164,8051.4425,6722.6436,5109.8562,15036.7700
25,20210101,1,11110,194154.3309,4879.7970,2966.6346,4444.9109,7789.4261,8261.5465,6570.5785,...,7401.0115,6565.2673,7181.0013,7165.6430,8504.7312,7385.7126,8060.0468,6695.7099,5121.4697,15114.7826
50,20210101,2,11110,194183.9935,4898.3821,2979.5495,4457.1672,7767.6170,8234.2491,6553.6145,...,7378.5379,6574.5843,7177.9484,7169.7808,8496.7149,7367.8450,8087.2472,6726.2882,5139.1388,15157.9449
75,20210101,3,11110,194442.1319,4947.3670,2996.0231,4482.1046,7802.1764,8211.2788,6569.2021,...,7391.0391,6508.0490,7145.9996,7215.3292,8489.2641,7389.1070,8091.7422,6753.6434,5175.5070,15191.7639
100,20210101,4,11110,194399.4872,4937.3379,2994.4045,4473.4720,7795.2318,8211.5085,6566.3434,...,7390.9195,6514.3597,7133.7941,7224.8924,8439.9604,7383.9978,8128.3648,6732.5720,5182.0422,15220.8846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218875,20211231,19,11110,245227.7420,4657.1400,2738.6257,5292.5463,10107.0561,11679.8512,9859.2908,...,12490.2211,9584.7426,9561.7162,8519.1273,10148.3260,9234.1440,9607.9289,7883.3662,5870.4229,15046.8233
218900,20211231,20,11110,231489.2787,4720.0435,2769.0048,5104.1484,9928.8167,10996.4135,9141.1127,...,11563.7422,8795.0133,9019.0955,7981.2519,9662.9437,8711.0867,8997.5533,7435.3756,5724.6851,14881.9262
218925,20211231,21,11110,214408.4066,4770.4016,2801.4391,4788.3916,8948.3523,9646.6547,8061.5391,...,9847.4885,7796.2563,8430.8929,7559.7530,9213.7811,8205.2552,8486.8119,6945.5770,5469.9344,14680.7902
218950,20211231,22,11110,205079.3731,4626.6108,2724.7156,4682.9460,8416.0299,9039.0183,7472.2433,...,8861.7496,6902.5702,7768.7999,7194.8614,9145.9240,7870.4603,8360.9091,6818.6640,5372.0326,14938.3204
218975,20211231,23,11110,200178.1168,4776.8307,2834.0809,4778.7504,8183.3739,8538.4679,7226.5802,...,8512.7530,6673.5000,7726.4749,6968.4889,8734.9742,7657.3277,8167.1724,6680.6381,5262.1168,14704.1677

In [8]:
gu = """11110 종로구
11140 중구
11170 용산구
11200 성동구
11215 광진구
11230 동대문구
11260 중랑구
11290 성북구
11305 강북구
11320 도봉구
11350 노원구
11380 은평구
11410 서대문구
11440 마포구
11470 양천구
11500 강서구
11530 구로구
11545 금천구
11560 영등포구
11590 동작구
11620 관악구
11650 서초구
11680 강남구
11710 송파구
11740 강동구"""
gu

'11110 종로구\n11140 중구\n11170 용산구\n11200 성동구\n11215 광진구\n11230 동대문구\n11260 중랑구\n11290 성북구\n11305 강북구\n11320 도봉구\n11350 노원구\n11380 은평구\n11410 서대문구\n11440 마포구\n11470 양천구\n11500 강서구\n11530 구로구\n11545 금천구\n11560 영등포구\n11590 동작구\n11620 관악구\n11650 서초구\n11680 강남구\n11710 송파구\n11740 강동구'

In [9]:
gu_list = gu.split("\n")

gu_name = {}
for gl in gu_list:
    key = int(gl.split()[0])
    val = gl.split()[1]
    gu_name[key] = val
gu_name

{11110: '종로구',
 11140: '중구',
 11170: '용산구',
 11200: '성동구',
 11215: '광진구',
 11230: '동대문구',
 11260: '중랑구',
 11290: '성북구',
 11305: '강북구',
 11320: '도봉구',
 11350: '노원구',
 11380: '은평구',
 11410: '서대문구',
 11440: '마포구',
 11470: '양천구',
 11500: '강서구',
 11530: '구로구',
 11545: '금천구',
 11560: '영등포구',
 11590: '동작구',
 11620: '관악구',
 11650: '서초구',
 11680: '강남구',
 11710: '송파구',
 11740: '강동구'}

In [10]:
df_gu["구"] = df_gu["자치구코드"].map(gu_name)

In [11]:
df_gu[["자치구코드", "구"]]

        자치구코드    구
0       11110  종로구
1       11140   중구
2       11170  용산구
3       11200  성동구
4       11215  광진구
...       ...  ...
218995  11620  관악구
218996  11650  서초구
218997  11680  강남구
218998  11710  송파구
218999  11740  강동구

[219000 rows x 2 columns]

In [12]:
df_gu = df_gu[['기준일ID', '시간대구분', '자치구코드', '구', '총생활인구수', '남자0세부터9세생활인구수', '남자10세부터14세생활인구수','남자15세부터19세생활인구수', '남자20세부터24세생활인구수', '남자25세부터29세생활인구수','남자30세부터34세생활인구수', '남자35세부터39세생활인구수', '남자40세부터44세생활인구수','남자45세부터49세생활인구수', '남자50세부터54세생활인구수', '남자55세부터59세생활인구수','남자60세부터64세생활인구수', '남자65세부터69세생활인구수', '남자70세이상생활인구수', '여자0세부터9세생활인구수','여자10세부터14세생활인구수', '여자15세부터19세생활인구수', '여자20세부터24세생활인구수','여자25세부터29세생활인구수', '여자30세부터34세생활인구수', '여자35세부터39세생활인구수','여자40세부터44세생활인구수', '여자45세부터49세생활인구수', '여자50세부터54세생활인구수','여자55세부터59세생활인구수', '여자60세부터64세생활인구수', '여자65세부터69세생활인구수', '여자70세이상생활인구수']]

In [13]:
df_gu.head(20)

,기준일ID,시간대구분,자치구코드,구,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20210101,0,11110,종로구,194924.6184,4920.3837,2992.2011,4479.0239,7799.4338,8270.0476,...,7513.2691,6532.6210,7281.9873,7159.4938,8479.3144,7389.4164,8051.4425,6722.6436,5109.8562,15036.7700
1,20210101,0,11140,중구,148826.8808,3354.1662,1376.5528,2368.3576,4868.7237,6945.7261,...,7110.3397,6713.5499,7244.8277,5420.8522,5795.2854,4829.2206,5617.3479,4846.5084,3847.0501,9823.1857
2,20210101,0,11170,용산구,250141.2136,7083.5939,3542.5572,5294.7572,7602.9197,9970.4226,...,10681.6414,11129.4982,12831.7555,10190.8974,10715.4628,8839.3659,9417.1985,8353.8373,5899.2935,16888.6424
3,20210101,0,11200,성동구,315490.0745,11513.7075,4873.2608,6427.3620,9447.8712,12296.0848,...,12707.7943,13462.4842,15997.2596,12525.5609,12903.9998,10991.7768,12442.7269,10785.3456,7925.9533,20678.4090
4,20210101,0,11215,광진구,360268.0149,10668.3623,5764.4680,9216.3402,12610.7515,16765.3160,...,17406.2677,15460.2633,15679.1837,13760.7719,14761.8863,13689.3575,14573.9438,12408.8341,8957.7143,20651.2597
5,20210101,0,11230,동대문구,342059.9682,10938.1169,5476.0155,7603.0251,12478.3163,15056.8483,...,13741.6065,12506.3745,13914.3666,11815.5846,12893.2048,11530.8968,13037.6240,11985.8662,9104.3384,26694.3864
6,20210101,0,11260,중랑구,386959.7457,13243.0990,6394.2681,8305.9946,10447.9222,13820.6633,...,14653.4088,14198.8097,16051.8943,13238.1608,15328.4239,15761.9749,18174.6318,15568.5015,11342.0475,29085.3077
7,20210101,0,11290,성북구,435615.8069,16334.4940,9144.1556,11712.3019,14685.4255,16050.0049,...,15537.6921,14515.8665,17257.0066,16451.5818,18783.3484,16574.9896,17024.5729,14877.7290,11677.7267,33390.2938
8,20210101,0,11305,강북구,321499.2460,10110.8400,5533.3059,7589.0850,9048.4191,11156.4150,...,11109.4807,9171.3979,11450.5343,10812.6171,14009.8503,12823.4228,14292.2059,12751.4971,10393.9179,30206.5473
9,20210101,0,11320,도봉구,296385.3026,10140.9560,5664.4778,7577.3841,8031.5565,9539.2771,...,9904.7917,9285.2006,10979.5935,9849.5634,12784.1343,12074.5044,14033.4412,12688.1718,9435.9320,25020.5546
10,20210101,0,11350,노원구,545243.3020,20252.3996,13563.3658,18743.9838,18014.5057,16714.3443,...,16259.3895,16343.1486,19448.3849,20623.6063,25546.6215,22298.1177,23542.7291,20480.7457,15377.9340,41902.0042
11,20210101,0,11380,은평구,484332.8760,17512.5360,9611.7970,12547.3676,12706.2755,15935.1377,...,17752.2495,17996.5417,21647.2447,19019.3782,21457.8046,18569.7455,21063.1627,18485.7323,13803.5313,37902.1672
12,20210101,0,11410,서대문구,341703.6997,10770.1924,5349.1034,7978.1313,11195.1980,13940.5656,...,15216.0788,13266.2028,14834.8719,12625.4489,14230.6414,12723.9315,14006.9657,11756.7235,8290.2062,24329.6483
13,20210101,0,11440,마포구,401866.1815,13570.1543,6717.5001,8854.5326,12651.9801,17699.1612,...,20337.7767,19280.7816,20521.5399,17373.0380,17657.4464,13466.2971,13844.3019,11878.0725,8281.4866,24130.9291
14,20210101,0,11470,양천구,407284.6425,16816.2226,11903.7292,14903.9376,10449.0773,11978.3853,...,12518.3244,12663.9244,15932.4363,17513.8274,19669.9133,16145.9969,16408.7716,14167.8742,10604.5188,24546.8505
15,20210101,0,11500,강서구,547287.6698,21252.2407,9823.8216,12343.9562,12998.6650,21088.3663,...,24189.5157,24697.9847,25547.4377,21536.5188,21592.2659,18227.5696,21849.5393,19937.0662,15136.3148,35855.3535
16,20210101,0,11530,구로구,387646.4657,14777.8570,6597.3461,8303.6101,9117.7298,13907.5027,...,14096.1702,15087.3151,17115.8292,15228.5973,15927.3993,13976.6918,16092.1669,14410.4297,10825.6636,24991.0809
17,20210101,0,11545,금천구,201969.1581,5654.6444,2680.7341,3496.0966,5724.2644,9711.6731,...,8513.5362,8362.4944,8439.9434,6858.2576,7702.8655,7314.4870,8712.8258,7381.8858,5633.9883,12405.9044
18,20210101,0,11560,영등포구,392741.4175,12248.3358,5477.9987,7743.7980,10087.9136,16829.5650,...,17887.0577,18731.1811,19056.6001,15021.2338,14783.6803,13561.3963,15232.8550,13143.8861,9738.6367,23515.8181
19,20210101,0,11590,동작구,392424.7747,13342.3054,6329.2556,8476.5504,12938.2542,18792.3341,...,16912.3920,15429.6700,16707.7582,14546.3348,15482.4764,14020.0719,15717.7136,14276.4627,10935.2126,27372.9552

In [14]:
df_gu[df_gu["구"] == "종로구"].head(50)

,기준일ID,시간대구분,자치구코드,구,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20210101,0,11110,종로구,194924.6184,4920.3837,2992.2011,4479.0239,7799.4338,8270.0476,...,7513.2691,6532.6210,7281.9873,7159.4938,8479.3144,7389.4164,8051.4425,6722.6436,5109.8562,15036.7700
25,20210101,1,11110,종로구,194154.3309,4879.7970,2966.6346,4444.9109,7789.4261,8261.5465,...,7401.0115,6565.2673,7181.0013,7165.6430,8504.7312,7385.7126,8060.0468,6695.7099,5121.4697,15114.7826
50,20210101,2,11110,종로구,194183.9935,4898.3821,2979.5495,4457.1672,7767.6170,8234.2491,...,7378.5379,6574.5843,7177.9484,7169.7808,8496.7149,7367.8450,8087.2472,6726.2882,5139.1388,15157.9449
75,20210101,3,11110,종로구,194442.1319,4947.3670,2996.0231,4482.1046,7802.1764,8211.2788,...,7391.0391,6508.0490,7145.9996,7215.3292,8489.2641,7389.1070,8091.7422,6753.6434,5175.5070,15191.7639
100,20210101,4,11110,종로구,194399.4872,4937.3379,2994.4045,4473.4720,7795.2318,8211.5085,...,7390.9195,6514.3597,7133.7941,7224.8924,8439.9604,7383.9978,8128.3648,6732.5720,5182.0422,15220.8846
125,20210101,5,11110,종로구,194825.6142,4908.9814,2987.0663,4443.3737,7752.6373,8224.3226,...,7426.6817,6524.7990,7152.1133,7201.1589,8428.2156,7390.8609,8171.5271,6808.1360,5210.3107,15214.6043
150,20210101,6,11110,종로구,196362.8379,4908.7107,2979.0161,4537.7217,7851.2289,8329.9147,...,7561.8135,6626.1450,7195.7932,7187.4643,8499.0904,7415.6882,8219.5470,6859.5943,5195.9341,15242.6679
175,20210101,7,11110,종로구,198658.8464,4920.2239,2985.9530,4526.1330,7948.5649,8513.6506,...,7597.3046,6702.7768,7190.5626,7216.1750,8615.3111,7479.2938,8301.5964,6964.3416,5220.9065,15206.8825
200,20210101,8,11110,종로구,198799.2959,4899.2537,2970.4513,4433.7223,7859.0340,8551.8584,...,7603.9023,6730.5870,7260.1052,7302.0979,8578.8606,7544.9791,8349.6158,7013.0352,5310.2059,15313.0395
225,20210101,9,11110,종로구,201379.0132,4813.2259,2924.4560,4367.3945,7958.7350,8693.4551,...,7689.2626,6794.4907,7371.0428,7369.8832,8678.1240,7658.7820,8488.5377,7221.9475,5396.9280,15561.1233
250,20210101,10,11110,종로구,204252.9071,4865.7259,2949.7424,4367.8008,8056.9927,8807.1031,...,7838.2776,6875.8111,7554.0013,7444.9483,8814.4032,7781.2558,8667.4241,7370.8715,5460.4963,15751.6772
275,20210101,11,11110,종로구,209877.2384,5120.6514,3070.1509,4467.3548,8222.7580,8900.8925,...,8071.4975,7024.3620,7787.1803,7555.4895,8868.8220,8044.6322,8802.8893,7481.4371,5497.3689,15878.9035
300,20210101,12,11110,종로구,212782.9688,5179.3560,3075.8558,4526.0652,8160.7079,9131.3839,...,8234.2071,7312.2175,7897.1819,7661.5117,9114.9770,8204.3310,9011.2523,7480.3400,5432.7891,15966.1622
325,20210101,13,11110,종로구,215723.0619,5138.1804,3051.5165,4526.5047,8252.3193,9317.5167,...,8479.6468,7368.2964,8063.7022,7743.1799,9306.5217,8260.2083,9088.5711,7497.5396,5430.8324,15761.5458
350,20210101,14,11110,종로구,219904.7822,5270.7226,3109.1427,4615.0158,8426.8211,9451.0769,...,8916.7699,7827.9981,8409.7861,7826.7864,9433.3677,8328.0568,9173.7903,7623.0458,5406.5736,15830.4131
375,20210101,15,11110,종로구,219103.3064,5451.9056,3197.0784,4612.6794,8629.9573,9628.3032,...,8915.7710,7791.3651,8208.6236,7742.0931,9485.1593,8194.6228,8951.8518,7562.0424,5439.3613,15754.7884
400,20210101,16,11110,종로구,215308.7090,5276.2420,3119.3910,4660.4637,8727.1217,9633.6661,...,8875.4407,7663.4931,8071.3270,7547.1661,9189.0640,8162.1922,8796.7759,7369.5126,5346.5474,15662.4386
425,20210101,17,11110,종로구,209954.8478,5370.5083,3145.3878,4639.4156,8698.2512,9593.7979,...,8773.0298,7490.1377,7759.3320,7379.5635,9007.4554,7930.1157,8543.3754,7142.0527,5279.2776,15348.1484
450,20210101,18,11110,종로구,205785.3082,5106.2060,3022.5104,4550.2583,8726.4625,9488.5010,...,8515.1207,7321.3315,7561.5792,7200.4012,8873.3286,7721.4673,8427.4082,7021.9947,5193.7249,15349.0911
475,20210101,19,11110,종로구,202153.0249,5126.1198,3038.3877,4532.7741,8476.7316,9288.7405,...,8305.4298,7127.5062,7403.2412,7146.9620,8672.6178,7558.4184,8236.9164,6927.3137,5158.3759,15306.8972
500,20210101,20,11110,종로구,198882.9400,5083.2976,3020.2054,4441.0547,8412.4670,9037.4511,...,7834.4953,6788.9769,7271.0084,7096.3206,8627.0050,7515.7861,8238.5334,6820.5118,5177.3290,15165.1341
525,20210101,21,11110,종로구,193463.2748,5017.6096,3013.9562,4411.8653,8052.9990,8470.3379,...,7282.4233,6379.6183,7009.8600,7000.0630,8504.2122,7469.8405,8058.2803,6552.2753,5126.1149,15128.4384
550,20210101,22,11110,종로구,191707.9277,4992.7680,3008.4033,4409.0591,7943.3151,8303.2075,...,7034.2521,6279.1122,6951.9527,6997.0227,8405.9294,7483.3827,8032.0437,6595.8096,5061.7306,15079.0090
575,20210101,23,11110,종로구,189135.9203,4918.2311,2973.3630,4286.0154,7753.1449,8085.6292,...,6935.4025,6100.4946,6903.2874,6901.0799,8307.7518,7253.3050,7913.9850,6606.7415,5042.7170,14989.9088
600,20210102,0,11110,종로구,188979.6178,4952.3865,2991.9707,4278.0629,7720.7439,8073.4247,...,6912.5080,6112.0481,6864.5287,6896.3444,8331.9627,7290.3161,7933.2251,6619.5519,5035.5519,14977.2193
625,20210102,1,11110,종로구,188892.1336,4909.2453,2982.7122,4281.9073,7727.4178,8038.1468,...,6955.8398,6132.9876,6817.3440,6879.9962,8325.3962,7286.8529,7943.5937,6626.6954,5038.9856,15011.2532
650,20210102,2,11110,종로구,188829.9357,4887.7139,2968.6123,4314.7315,7748.0666,8004.7152,...,6904.6622,6087.4787,6829.6409,6867.5911,8310.0538,7281.9710,7994.4851,6645.5836,5069.8195,15062.4807
675,20210102,3,11110,종로구,188846.6534,4850.2197,2946.4835,4289.4507,7761.5450,8074.8118,...,6891.5656,6077.4436,6833.7211,6882.3956,8302.9522,7295.7184,7979.4685,6679.3922,5065.1112,15087.0534
700,20210102,4,11110,종로구,189581.8311,4878.1386,2969.4056,4285.4361,7769.9078,8054.6405,...,6922.0107,6088.7918,6830.2021,6909.9074,8306.2659,7332.4172,8027.8256,6716.6187,5082.4757,15147.1304
725,20210102,5,11110,종로구,190842.1019,4834.7143,2938.6207,4277.3825,7765.3264,8117.8989,...,6940.1363,6103.3203,6863.5890,6909.4357,8364.5096,7364.6708,8123.0430,6853.1829,5132.6780,15163.4826
750,20210102,6,11110,종로구,193155.2035,4820.2533,2922.7814,4275.3963,7778.0688,8208.7098,...,7104.8175,6238.0061,6883.2936,6923.8231,8400.4571,7438.3438,8242.9791,6938.8585,5224.2433,15182.3129
775,20210102,7,11110,종로구,196271.1080,4882.6694,2946.2555,4297.7200,7856.5940,8403.6949,...,7150.9296,6282.3383,6992.8492,6960.2545,8476.6225,7509.5567,8325.3584,7014.1101,5308.4461,15253.6348
800,20210102,8,11110,종로구,201594.5517,4925.8531,2964.7683,4294.4054,7861.6138,8579.6352,...,7379.2670,6619.6801,7225.7419,7120.0421,8611.8782,7741.4715,8589.2231,7268.3331,5453.0923,15483.1104
825,20210102,9,11110,종로구,207972.5025,4927.8327,2973.5338,4306.2790,8006.6269,8801.7579,...,7723.0977,6863.8375,7341.2331,7416.0213,8854.7017,8194.4368,8856.1612,7576.5499,5630.4067,15644.1252
850,20210102,10,11110,종로구,214702.3062,5046.6370,3052.1656,4412.3980,8087.5099,9124.1920,...,8092.5847,7091.3479,7735.2053,7596.1021,9144.2311,8379.0434,9230.4284,7758.0860,5779.0024,15775.7330
875,20210102,11,11110,종로구,222958.6106,5050.5573,3038.4211,4456.9791,8199.2185,9367.9949,...,8536.5051,7546.2972,8073.7364,7964.5755,9547.2080,8712.1379,9572.6082,8076.7978,5840.3528,16491.8276
900,20210102,12,11110,종로구,230285.5522,5215.8316,3084.8775,4450.0361,8316.1894,9716.9179,...,8983.8236,8006.2929,8201.9545,8312.5188,9889.3013,9020.4928,9736.7261,8303.0215,5953.7924,16482.3010
925,20210102,13,11110,종로구,235607.3174,5268.7926,3152.1453,4553.3784,8449.9305,10264.9135,...,9652.0759,8230.9678,8556.0005,8638.7872,9949.6714,9275.2547,9859.3619,8482.0850,5892.1106,16385.1833
950,20210102,14,11110,종로구,239232.0686,5536.3174,3230.6884,4457.3612,8594.1960,10487.0894,...,10171.6003,8678.3387,8733.8700,8779.3271,10107.8697,9216.9400,9942.5672,8344.2037,6012.9887,16432.1419
975,20210102,15,11110,종로구,238218.6663,5400.1059,3145.5012,4573.7039,8858.5343,10743.1501,...,10522.6480,8823.9406,8745.7634,8791.1298,9969.7779,9079.6991,9541.6463,8264.3513,5985.4253,16413.4942
1000,20210102,16,11110,종로구,231260.0457,5281.7083,3070.1194,4615.2684,8801.0391,10803.3876,...,10418.9845,8497.3842,8637.7008,8506.2527,9481.7908,8678.9467,9466.5790,7854.4424,5793.4709,15907.2822
1025,20210102,17,11110,종로구,223659.9290,5230.3322,3045.0209,4516.2614,8879.3052,10619.8874,...,10004.5809,8293.4339,8251.3983,8091.4052,9270.5933,8375.6880,9032.0706,7471.4720,5603.2381,15384.8418
1050,20210102,18,11110,종로구,214893.3545,4985.2176,2939.9444,4395.6570,8769.0775,10263.8205,...,9562.6999,7888.0244,7997.0311,7760.1564,8985.2227,8079.7258,8673.0413,7171.4649,5355.8135,15092.4470
1075,20210102,19,11110,종로구,209347.5985,4959.5841,2933.7294,4444.8880,8623.7013,9931.7675,...,9118.7814,7570.0581,7838.8071,7465.6081,8803.7319,7923.8615,8581.0043,7023.9989,5293.7592,14965.3145
1100,20210102,20,11110,종로구,203393.1963,4849.9569,2922.5622,4258.8080,8559.5028,9493.5723,...,8492.4745,7169.5183,7642.3017,7326.2239,8650.7877,7755.7999,8312.2018,6844.4949,5261.5865,14914.7670
1125,20210102,21,11110,종로구,196332.1934,4842.6691,2923.7333,4385.6901,8217.7643,8836.0413,...,7736.5588,6764.0479,7278.7789,7118.9800,8493.1177,7613.2426,8020.4313,6624.6252,5129.9552,14808.8371
1150,20210102,22,11110,종로구,195189.2206,4853.3435,2960.8985,4269.2656,8131.4951,8529.1487,...,7599.7327,6616.5305,7083.7150,7135.0801,8482.2530,7563.7963,8071.4380,6640.4032,5122.6717,14887.7245
1175,20210102,23,11110,종로구,192357.9886,4836.2099,2938.4290,4267.6024,7945.9250,8327.8538,...,7412.4022,6395.8043,7146.6415,6988.8480,8372.6149,7411.1796,8046.9497,6575.8880,5017.5134,14875.0338
1200,20210103,0,11110,종로구,191728.8361,4823.8914,2936.8912,4306.4303,7802.7449,8227.4966,...,7311.7103,6390.2381,7087.2140,6974.4149,8449.2261,7445.4889,8006.6001,6628.1166,5017.3145,14859.5420
1225,20210103,1,11110,종로구,191611.9075,4888.4120,2977.1655,4327.5693,7855.7786,8242.8487,...,7255.7040,6375.0909,7103.7716,6999.0605,8447.8295,7430.7941,7982.7042,6641.6569,5021.2060,14884.4302

In [15]:
df_gu.columns

Index(['기준일ID', '시간대구분', '자치구코드', '구', '총생활인구수', '남자0세부터9세생활인구수',
       '남자10세부터14세생활인구수', '남자15세부터19세생활인구수', '남자20세부터24세생활인구수',
       '남자25세부터29세생활인구수', '남자30세부터34세생활인구수', '남자35세부터39세생활인구수',
       '남자40세부터44세생활인구수', '남자45세부터49세생활인구수', '남자50세부터54세생활인구수',
       '남자55세부터59세생활인구수', '남자60세부터64세생활인구수', '남자65세부터69세생활인구수', '남자70세이상생활인구수',
       '여자0세부터9세생활인구수', '여자10세부터14세생활인구수', '여자15세부터19세생활인구수',
       '여자20세부터24세생활인구수', '여자25세부터29세생활인구수', '여자30세부터34세생활인구수',
       '여자35세부터39세생활인구수', '여자40세부터44세생활인구수', '여자45세부터49세생활인구수',
       '여자50세부터54세생활인구수', '여자55세부터59세생활인구수', '여자60세부터64세생활인구수',
       '여자65세부터69세생활인구수', '여자70세이상생활인구수'],
      dtype='object')

In [16]:
df_gu = df_gu.drop(columns = {'남자0세부터9세생활인구수', '남자10세부터14세생활인구수','남자15세부터19세생활인구수', '남자20세부터24세생활인구수', '남자25세부터29세생활인구수','남자30세부터34세생활인구수', '남자35세부터39세생활인구수', '남자40세부터44세생활인구수','남자45세부터49세생활인구수', '남자50세부터54세생활인구수', '남자55세부터59세생활인구수','남자60세부터64세생활인구수', '남자65세부터69세생활인구수', '남자70세이상생활인구수', '여자0세부터9세생활인구수','여자10세부터14세생활인구수', '여자15세부터19세생활인구수', '여자20세부터24세생활인구수','여자25세부터29세생활인구수', '여자30세부터34세생활인구수', '여자35세부터39세생활인구수','여자40세부터44세생활인구수', '여자45세부터49세생활인구수', '여자50세부터54세생활인구수','여자55세부터59세생활인구수', '여자60세부터64세생활인구수', '여자65세부터69세생활인구수', '여자70세이상생활인구수'})

In [17]:
df_gu["총생활인구수"] = df_gu["총생활인구수"].astype(int)

In [39]:
df_gu.head()

      기준일ID  시간대구분  자치구코드    구  총생활인구수
0  20210101      0  11110  종로구  194924
1  20210101      0  11140   중구  148826
2  20210101      0  11170  용산구  250141
3  20210101      0  11200  성동구  315490
4  20210101      0  11215  광진구  360268

In [42]:
test = list(df_gu["구"].unique())
test

['종로구',
 '중구',
 '용산구',
 '성동구',
 '광진구',
 '동대문구',
 '중랑구',
 '성북구',
 '강북구',
 '도봉구',
 '노원구',
 '은평구',
 '서대문구',
 '마포구',
 '양천구',
 '강서구',
 '구로구',
 '금천구',
 '영등포구',
 '동작구',
 '관악구',
 '서초구',
 '강남구',
 '송파구',
 '강동구']

In [54]:
test_2 = []
for x in test:
    test_1 = df_gu[df_gu["구"] == x]["총생활인구수"].mean()
    test_2.append((test_1))

In [58]:
test_2

[266700.12557077623,
 243922.93778538812,
 278545.25034246576,
 340105.7163242009,
 354361.6380136986,
 343346.56130136986,
 351437.0134703196,
 415883.5119863014,
 294209.2444063927,
 274932.4172374429,
 508079.6147260274,
 435180.7396118721,
 353611.50171232875,
 438452.3941780822,
 384186.37682648405,
 538722.9683789954,
 382433.15342465753,
 218657.50331050227,
 458186.60924657533,
 377429.7188356164,
 469003.7649543379,
 555706.1658675799,
 786140.6006849315,
 735114.5710045662,
 503064.675913242]

In [73]:
person = pd.DataFrame(data = list(zip(test,test_2)), columns = ["구", "총생활인구수"])
person

       구         총생활인구수
0    종로구  266700.125571
1     중구  243922.937785
2    용산구  278545.250342
3    성동구  340105.716324
4    광진구  354361.638014
5   동대문구  343346.561301
6    중랑구  351437.013470
7    성북구  415883.511986
8    강북구  294209.244406
9    도봉구  274932.417237
10   노원구  508079.614726
11   은평구  435180.739612
12  서대문구  353611.501712
13   마포구  438452.394178
14   양천구  384186.376826
15   강서구  538722.968379
16   구로구  382433.153425
17   금천구  218657.503311
18  영등포구  458186.609247
19   동작구  377429.718836
20   관악구  469003.764954
21   서초구  555706.165868
22   강남구  786140.600685
23   송파구  735114.571005
24   강동구  503064.675913

In [78]:
person["총생활인구수"] = person["총생활인구수"].astype(float).round(1)
person["총생활인구수"] = person["총생활인구수"].astype(int)
person["총생활인구수"].head()

0    266700
1    243922
2    278545
3    340105
4    354361
Name: 총생활인구수, dtype: int64

In [89]:
person.head()

     구  총생활인구수
0  종로구  266700
1   중구  243922
2  용산구  278545
3  성동구  340105
4  광진구  354361

In [88]:
sort_person = person.sort_values("총생활인구수", ascending = False)
sort_person

       구  총생활인구수
22   강남구  786140
23   송파구  735114
21   서초구  555706
15   강서구  538723
10   노원구  508079
24   강동구  503064
20   관악구  469003
18  영등포구  458186
13   마포구  438452
11   은평구  435180
7    성북구  415883
14   양천구  384186
16   구로구  382433
19   동작구  377429
4    광진구  354361
12  서대문구  353611
6    중랑구  351437
5   동대문구  343346
3    성동구  340105
8    강북구  294209
2    용산구  278545
9    도봉구  274932
0    종로구  266700
1     중구  243922
17   금천구  218657

In [75]:
person.to_csv("person.csv", encoding="cp949")

In [38]:
df_gu[df_gu["구"] == "강남구"]["총생활인구수"].mean()

786140.6006849315

In [52]:
crime = pd.read_csv("/Users/sangu/likelion_AIS/ais7/mid_project/mid_data/범죄시간.csv", encoding = "cp949")
crime

,범죄별(1),2014,2014.1,2014.2,2014.3,2014.4,2014.5,2014.6,2014.7,2014.8,...,2020,2020.1,2020.2,2020.3,2020.4,2020.5,2020.6,2020.7,2020.8,2020.9
0,범죄별(1),계,00:00-02:59,03:00-05:59,06:00-08:59,09:00-11:59,12:00-14:59,15:00-17:59,18:00-20:59,21:00-23:59,...,계,00:00-02:59,03:00-05:59,06:00-08:59,09:00-11:59,12:00-14:59,15:00-17:59,18:00-20:59,21:00-23:59,미상
1,절도,266784,21567,21195,17918,29081,30903,34679,40322,35015,...,180067,11789,13672,12392,21358,26743,28648,25809,19263,20393
2,살인,938,82,86,65,94,91,101,135,155,...,805,56,58,63,78,78,88,102,114,168
3,강도,1618,249,297,86,92,120,115,142,204,...,692,80,96,35,64,67,73,65,90,122
4,성폭력,29863,2511,2651,2275,2197,2330,3059,3576,4405,...,30105,2820,2808,1726,2207,2479,3054,3704,4992,6315
5,폭행,146625,20789,16233,7791,9147,9464,12069,18917,35198,...,143600,16548,14030,8244,10865,11842,14248,20033,30765,17025

In [64]:
c_df = pd.read_csv("/Users/sangu/likelion_AIS/ais7/mid_project/mid_data/범죄발생_시간_20221021110153.csv", encoding = "cp949")
c_df

   범죄별(1)       시간별(1)   2014   2015   2016   2017   2018   2019   2020
0      절도  00:00-02:59  21567  19607  15523  13751  12596  13095  11789
1      절도  03:00-05:59  21195  19561  15832  14385  13731  14176  13672
2      절도  06:00-08:59  17918  16584  13882  12502  12483  13104  12392
3      절도  09:00-11:59  29081  26347  22982  21531  20672  21763  21358
4      절도  12:00-14:59  30903  29451  26400  24623  24578  27242  26743
5      절도  15:00-17:59  34679  32626  28570  26890  26672  28582  28648
6      절도  18:00-20:59  40322  35789  29490  26654  25697  27272  25809
7      절도  21:00-23:59  35015  30570  25140  22167  19984  20587  19263
8      살인  00:00-02:59     82     74     77     67     65     49     56
9      살인  03:00-05:59     86     85     70     69     57     73     58
10     살인  06:00-08:59     65     73     75     75     63     49     63
11     살인  09:00-11:59     94    108     98     94     91     86     78
12     살인  12:00-14:59     91     84    102     88     78     97     78
13     살인  15:00-17:59    101    114    122    100     77     96     88
14     살인  18:00-20:59    135    137    109    126    133    110    102
15     살인  21:00-23:59    155    156    193    141    140    132    114
16     강도  00:00-02:59    249    232    150    132    112    112     80
17     강도  03:00-05:59    297    262    200    162    135    133     96
18     강도  06:00-08:59     86     79     78     58     49     45     35
19     강도  09:00-11:59     92    110     77     72     76     66     64
20     강도  12:00-14:59    120    102    107     77     68     75     67
21     강도  15:00-17:59    115     93     86     90     67     72     73
22     강도  18:00-20:59    142    147    136    100     90     86     65
23     강도  21:00-23:59    204    186    142    136     98    112     90
24    성폭력  00:00-02:59   2511   2518   2897   3200   3054   3061   2820
25    성폭력  03:00-05:59   2651   2665   2852   3296   3250   3332   2808
26    성폭력  06:00-08:59   2275   2465   2202   2615   2246   2233   1726
27    성폭력  09:00-11:59   2197   2122   1996   2559   2394   2317   2207
28    성폭력  12:00-14:59   2330   2473   2241   2651   2615   2539   2479
29    성폭력  15:00-17:59   3059   3262   2894   3442   3327   3204   3054
30    성폭력  18:00-20:59   3576   3826   3710   4335   4034   3920   3704
31    성폭력  21:00-23:59   4405   4635   4903   5303   5086   5048   4992
32     폭행  00:00-02:59  20789  22467  23719  22343  20672  19898  16548
33     폭행  03:00-05:59  16233  18015  19177  18552  17595  17036  14030
34     폭행  06:00-08:59   7791   8883   9995   9738   9728   9618   8244
35     폭행  09:00-11:59   9147  10576  11605  11575  12137  11964  10865
36     폭행  12:00-14:59   9464  10695  11862  11798  12310  12867  11842
37     폭행  15:00-17:59  12069  13315  14426  14291  14971  15132  14248
38     폭행  18:00-20:59  18917  20874  22387  21375  21459  21178  20033
39     폭행  21:00-23:59  35198  38481  40428  38210  36140  34873  30765

In [60]:
c_df["범죄별(1)"].unique()

array(['계', '절도', '살인', '강도', '방화', '성폭력', '폭행', '상해', '협박', '공갈',
       '약취와유인', '체포와감금', '폭력행위등(손괴·강요·주거침입등)', '폭력행위등(단체등의구성·활동)',
       '도박과복표', '과실치사상', '업무상과실치사상', '가정폭력범죄의처벌등에관한특례법', '경범죄처벌법',
       '교통사고처리특례법', '도로교통법', '도로교통법(무면허운전)', '도로교통법(사고후미조치)',
       '도로교통법(음주운전)', '도로교통법(음주측정거부)', '마약류관리에관한법률(대마)', '마약류관리에관한법률(마약)',
       '마약류관리에관한법률(향정)', '성매매알선등행위의처벌에관한법률', '아동·청소년의성보호에관한법률(성매수등)',
       '아동·청소년의성보호에관한법률(성착취물등)', '특가법(도주차량)'], dtype=object)